/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package YzlmMuh;

import java.util.ArrayList;
import java.util.function.BooleanSupplier;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    }

    public static boolean search(ArrayList<Integer> array,int e) {
        if(array==null) return false;
        for(int elt:array){
            if(elt==e) return true;
        }



        return false;
        
    }

    
}
